sudo: required
language: python
services:
- docker
before_install:
- sudo apt-get -qq update
install:
- pip install molecule==1.25.0
- pip install ansible==2.3.2.0
- pip install docker
script:
- molecule test --driver docker
notifications:
  slack:
    secure: NkXLah+16ZVdsgr7LkuLh0UK6boHPkP8LCefwVpR2Ve6n+nNvS4A+1mEiGxbCIwJXXdldeRoPEDbbGPDWckhEXQyUUjhP7ghXx2bWWs8WpcJ43JF80mQNba1VL0lm9KKfkYRQh6KEG2upXF60JV6PmvaQ3bSrF3jCRfL4GChA+h8kRUMXec1FMN9EXTIwWS5fCg1zESSyChTdR2ovRkwvlsjEPpcqRStb09iVe35SC7t66r6jwwZpFNCFK5y8CAEKcTHsvFxmrAOkWIjWY+BWSesuIifOA9buKOF2zMvq7Rn3mRKnktttTEg94eYZGIingm+Ps/Xk+7NBQOMUBJIyCS/7vmgzjrO9z2o5th1lBybk4J4uJVTG/HnbjnJ6RrAFn5Q/KW4cK00eSPCR8juYi9DMAUZoNODEzYPSrPoq9T1mZrrX3HhwEzO/ty7fC6otENJ89Ez8OGv1DYuf8w5AfT0s9+c4bvKj5pn3AMQCSPc/CV/x3faWDOa9HqQoL6J0LtnQQz3AVA5Ei1Pz088MHh2PxL51Ixe6NWZXNWqnOCAwWIwW4OGlTRdZ2WKyqIn+5ENfQFCVua2QvQQnBc5wJZTfH8gsjAfVvYM8dy9UVWjTIonihZ1+/Xvl43lHsXcC5C33o0taIdk4zshAXXVyCJ7XtlQnkm5XNNl8iumDxI=
